# This is a test for executing java files after a commit
name: My First Pipeline
run-name: "Pipeline run by @${{ github.actor }} | Trigger ${{ github.event_name }} | Execution # ${{ github.run_number }}"

# When the work will run:
on:
  push:
    branches: # Instead of list can also be declared as  branches: ["!main
      - '**'
      - '!main'
  workflow_dispatch: # This event will only trigger a workflow run if the workflow file exists on the default branch.
  
# Jobs declaration
jobs:
  # Build program
  build:
    runs-on: [self-hosted]
    steps:
      - name: Test output
        run: echo "This is a test"
        
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Setup Java environment
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'oracle'
          java-version: '23.0.2'

      - name: Compile into Class objects
        run: javac HelloWorld/src/* -d HelloWorld/bin
      
      - name: Execute compiled programs
        run: java -cp HelloWorld/bin --enable-preview Variables
